insert into communities (slug, name, description, category, min_tier, member_count, rules) values
('the-pit', 'The Pit', 'Open lounge of the floor. Deal chatter, weekly notes, and the tape.', 'mixed', 'ground', 18420, 'No paid shilling. Cite numbers. Disagreement is the product.'),
('due-diligence', 'Due Diligence', 'Long-form underwriting. Rent rolls, franchise FDD excerpts, title issues.', 'mixed', 'ground', 6120, 'Primary sources over vibes. Mark assumptions.'),
('apartments', 'Apartments', 'Fourplexes to garden-style. Occupancy, capex, and bad hallways.', 'apartments', 'second', 9400, 'Stay on residential. No land banking here.'),
('franchises', 'Franchises', 'QSR, service brands, and the royalty stack.', 'franchise', 'third', 4300, 'Disclose if you operate a competing unit.'),
('land-and-lots', 'Land & Lots', 'Entitlements, water, and dirt that does not yet cash flow.', 'land', 'fourth', 2100, 'Entitlement risk belongs in the first paragraph.'),
('wheels', 'Wheels', 'Touring coaches, production vans, collector books, and fleets.', 'wheels', 'fourth', 1880, 'Condition reports or it did not happen.'),
('predictions', 'Predictions', 'Markets on occupancy, rates, yields, and the city.', 'predictions', 'ground', 12100, 'No insider ops data from a live vault you sponsor.')
on conflict (slug) do nothing;

insert into vaults (slug, name, category, location, description, thesis, risk, target_cents, raised_cents, yield_bps, min_tier, min_check_cents, status, members, art_key, hold_years) values
('inglewood-fourplex', 'Inglewood Fourplex', 'apartments', 'Inglewood, CA',
 'A 4-unit 1962 walk-up two blocks off Market Street. Rents are 18% below street; we recap kitchens and hold.',
 'Inglewood is still mispriced versus the stadium corridor. Stabilized 6.4% on current rents, 7.8% after light value-add.',
 'Tenant turnover during rehab. Insurance in the FAIR-plan era.',
 185000000, 124400000, 640, 'second', 25000, 'open', 186, 'apartments', 7),
('golden-arches-socal', 'Golden Arches SoCal', 'franchise', 'Carson, CA',
 'Minority interest in a three-unit McDonald’s operator on the 405. Real estate owned by the syndicate; ops leased back.',
 'Royalty and rent cover debt with a 1.45x DSCR. We buy the dirt, not the fryer schedule.',
 'Brand agreement transfer. Labor inflation on crew.',
 420000000, 301500000, 910, 'third', 100000, 'open', 94, 'franchise', 10),
('antelope-valley-section', 'Antelope Valley Section', 'land', 'Lancaster, CA',
 '148 acres of entitled industrial-adjacent dirt with water table already studied. Hold, farm solar lease, or sell pads.',
 'Logistics wants cheap land inside a 90-minute port radius. Solar lease pays the carry until a pad sale.',
 'Entitlement drift. Water adjudication.',
 610000000, 188000000, 420, 'fourth', 250000, 'open', 41, 'land', 8),
('west-coast-tour-fleet', 'West Coast Tour Fleet', 'wheels', 'Burbank, CA',
 'Eight Mercedes Sprinters and two Prevost coaches leased to mid-tier touring acts and a film-production house.',
 'Utilization ran 71% last year. Entertainment travel is back; coaches depreciate slower than the notes.',
 'Idle winter. Driver insurance. Residual values.',
 275000000, 219800000, 1120, 'fourth', 150000, 'open', 67, 'wheels', 5),
('dtla-adaptive', 'DTLA Adaptive Reuse', 'commercial', 'Downtown Los Angeles',
 'Two vacant jewelry-district floors converting to creative office with ground-floor cafe lease already LOI’d.',
 'Vacancy is high; basis is 40% of replacement. Cafe lease covers a third of debt from day one.',
 'Conversion overruns. Office demand stays soft.',
 890000000, 412000000, 730, 'fourth', 500000, 'open', 38, 'commercial', 6),
('street-to-suite', 'Street-to-Suite Commons', 'mixed', 'South Los Angeles',
 'Open-membership fund stacking small checks into a rolling book of local mixed-use and corner retail.',
 'The floor should own the block it talks about. Diversified, slow, and boring on purpose.',
 'Small-asset ops load. Heterogeneous tenants.',
 250000000, 196200000, 510, 'ground', 2500, 'open', 2140, 'mixed', 5),
('rally-book-one', 'Rally Book One', 'wheels', 'Pasadena, CA',
 'A six-car collector book (1967–1991) that tours museum weekends and private rallies. Insured, stored, shown.',
 'The cars cash-flow from exhibition fees; the book is the upside. Penthouse only — illiquid and opinionated.',
 'Taste risk. Storage and conservation.',
 340000000, 276500000, 380, 'penthouse', 1000000, 'open', 22, 'rally', 9),
('crenshaw-solar-co', 'Crenshaw Solar Co-op', 'mixed', 'Crenshaw, CA',
 'Rooftop solar across a co-op of 40 small landlords. Power sold back; members take a pro-rata kWh yield.',
 'Utility rates only go one way. We finance the panels; landlords keep the roof.',
 'Inverter failures. Interconnection delays.',
 96000000, 81200000, 680, 'ground', 2500, 'open', 540, 'solar', 12)
on conflict (slug) do nothing;

insert into markets (slug, question, description, category, yes_price, volume_cents, traders, closes_at, status, related_vault_id) values
('inglewood-occ-q4', 'Will the Inglewood Fourplex hit 95% occupancy by year-end?',
 'Resolves YES if trailing-30 occupancy ≥ 95% on the last business day of December.', 'apartments', 61, 18400000, 412, now() + interval '108 days', 'open',
  (select id from vaults where slug = 'inglewood-fourplex')),
('arches-yield-12', 'Will Golden Arches SoCal print a 12%+ net yield this year?',
 'Net to members after fees, on contributed capital. Manager report is the resolution source.', 'franchise', 34, 22100000, 288, now() + interval '140 days', 'open',
  (select id from vaults where slug = 'golden-arches-socal')),
('fed-cut-dec', 'Will the Fed cut rates at least once before January?',
 'YES if the upper bound of the fed funds target is lower than today''s print on any meeting through December.', 'macro', 57, 91000000, 1904, now() + interval '90 days', 'open', null),
('la-rents-up', 'Will LA County asking rents finish the year up vs January?',
 'Zillow Observed Rent Index, county series. Up 0.1% counts.', 'apartments', 72, 15400000, 640, now() + interval '110 days', 'open', null),
('tour-util-70', 'Will the Tour Fleet run above 70% utilization this summer?',
 'Days under contract / available days, June–August, manager dashboard.', 'wheels', 68, 7200000, 156, now() + interval '45 days', 'open',
  (select id from vaults where slug = 'west-coast-tour-fleet')),
('av-pad-sale', 'Will Antelope Valley sell at least one pad before close of next year?',
 'A recorded sale or executed PSA with non-refundable deposit ≥ $1M.', 'land', 41, 11300000, 98, now() + interval '470 days', 'open',
  (select id from vaults where slug = 'antelope-valley-section')),
('dtla-cafe-open', 'Will the DTLA cafe tenant open by March?',
 'Certificate of occupancy plus public hours. Soft opening counts.', 'commercial', 53, 5400000, 121, now() + interval '180 days', 'open',
  (select id from vaults where slug = 'dtla-adaptive')),
('housing-starts-ca', 'Will California housing starts beat last year?',
 'Census Building Permits Survey, state annual. Beats last year''s count.', 'macro', 29, 18800000, 502, now() + interval '200 days', 'open', null),
('mcdonalds-same-store', 'Will US McDonald''s same-store sales finish positive?',
 'Company reported comparable sales, full year.', 'franchise', 48, 27600000, 733, now() + interval '160 days', 'open',
  (select id from vaults where slug = 'golden-arches-socal')),
('solar-interconnect', 'Will Crenshaw Solar interconnect 80% of roofs this year?',
 'Utility permission-to-operate on ≥ 32 of 40 contracted roofs.', 'energy', 44, 3900000, 210, now() + interval '120 days', 'open',
  (select id from vaults where slug = 'crenshaw-solar-co'))
on conflict (slug) do nothing;

insert into listings (seller_name, seller_handle, title, description, category, price_cents, location, status, art_key) values
('Nia Okonkwo', 'niao', 'Secondary: 1.2% of Inglewood Fourplex', 'Selling a slice of my Ground-era position. Transfer subject to vault docs. Trailing yield 6.1%.', 'secondary', 1480000, 'Inglewood, CA', 'open', 'paper'),
('Marcus Hale', 'mhale', '2019 Mercedes Sprinter 2500 — crew spec', '144k miles, racks, lithium, the van the Tour Fleet retired. Clean title. Inspection in Burbank.', 'vehicles', 6200000, 'Burbank, CA', 'open', 'van'),
('Priya Shah', 'priyas', 'FDD review — QSR, 5-day turn', 'Former franchise counsel. I mark up Item 19 and the real-estate addendum. Floor members only.', 'services', 180000, 'Remote', 'open', 'service'),
('Diego Ortega', 'diegoo', 'Off-market 8-unit teaser — Compton', 'Owner will take a syndicate. 7.1 cap on in-place. Intro fee if we close through the Floor.', 'deals', 0, 'Compton, CA', 'open', 'deal'),
('Elena Voss', 'elenav', '1973 BMW 2002tii — rally eligible', 'Not in Book One. I want it in a collective, not a garage. Full rust report attached in DD.', 'vehicles', 2850000, 'Pasadena, CA', 'open', 'car'),
('Jonah Park', 'jpark', 'Bookkeeping for small landlords', 'I run books for 11 Street-to-Suite assets. Taking four more buildings.', 'services', 90000, 'South LA', 'open', 'service'),
('Amina Ruiz', 'aminar', 'Secondary: Tour Fleet units', 'Need liquidity before a down payment. 0.4% of West Coast Tour Fleet.', 'secondary', 860000, 'Burbank, CA', 'open', 'paper'),
('Theo Brandt', 'tbrandt', 'Vintage neon for the DTLA cafe', 'Restored 1961 cocktail sign. The adaptive-reuse GP asked me to list it here first.', 'goods', 420000, 'Downtown LA', 'open', 'neon');

insert into posts (community_id, author_name, author_handle, author_tier, title, body, kind, upvotes, downvotes, comment_count, created_at) values
((select id from communities where slug='the-pit'), 'Nia Okonkwo', 'niao', 'third',
 'The floor is not a brokerage. Stop asking for hot tips.',
 'We pool checks into assets we can visit. If you want a ticker, there is a casino downstairs in Predictions — and that is fine, it is labeled. What is not fine is treating a fourplex like a meme. Read the rent roll or sit this one out.',
 'thread', 412, 38, 24, now() - interval '3 hours'),
((select id from communities where slug='due-diligence'), 'Marcus Hale', 'mhale', 'fourth',
 'Inglewood Fourplex — unit mix and the actual capex list',
 'Two 2-beds, two 1-beds. Roof is 2019. I walked it Tuesday. The 18% below-market is real on the 1-beds; the 2-beds are only 9% light because one tenant is a cousin of the seller. That lease rolls in March. Insurance quote came in at $14.2k, not the $9k in the teaser. Underwrite the higher number.',
 'dd', 890, 12, 41, now() - interval '9 hours'),
((select id from communities where slug='franchises'), 'Priya Shah', 'priyas', 'penthouse',
 'We are buying the dirt under the arches, not the Happy Meal',
 'If you cannot recite the difference between a franchise agreement and a ground lease, you are not on this vault. The operator stays. We collect rent. Item 19 in the FDD is the boring kind of good. AMA in the deal room Thursday.',
 'deal', 654, 22, 33, now() - interval '1 day'),
((select id from communities where slug='apartments'), 'Diego Ortega', 'diegoo', 'second',
 'Occupancy in Inglewood is a story about bus lines, not the stadium',
 'Everyone wants to underwrite SoFi. The fourplex tenants take the 115. If the city ever kills that line, your 6.4% is a 5. I still like the basis. I do not like stadium narratives in a rent roll.',
 'thread', 301, 44, 19, now() - interval '5 hours'),
((select id from communities where slug='wheels'), 'Elena Voss', 'elenav', 'fourth',
 'Tour Fleet utilization, June flash',
 '71% last year, 74% June MTD. The Prevost that sat in Q1 is on a 28-day with a country act. That is the whole business: expensive metal, boring contracts, someone else driving.',
 'dd', 277, 8, 14, now() - interval '6 hours'),
((select id from communities where slug='predictions'), 'Jonah Park', 'jpark', 'ground',
 'Why I am 61¢ YES on fourplex occupancy',
 'The March rollover plus two already-noticed vacant 1-beds. Rehab is kitchens, not plumbing. If insurance does not blow the budget, they lease by October. I sized it like a comment, not a conviction.',
 'market', 188, 31, 22, now() - interval '2 hours'),
((select id from communities where slug='land-and-lots'), 'Amina Ruiz', 'aminar', 'fourth',
 'Antelope Valley water memo, annotated',
 'The study is from 2022. Adjudication is slower than the teaser admits. I still want a pad sale more than a solar lease — the lease is a carry, not a thesis. Marking NO on the pad market until we see a PSA.',
 'dd', 240, 16, 11, now() - interval '14 hours'),
((select id from communities where slug='the-pit'), 'Theo Brandt', 'tbrandt', 'second',
 'Street-to-Suite just distributed again',
 '$11.40 per $1,000 this quarter. Tiny. That is the point. Commons funds should feel like a credit union that owns corner stores.',
 'thread', 520, 9, 28, now() - interval '4 hours'),
((select id from communities where slug='due-diligence'), 'Nia Okonkwo', 'niao', 'third',
 'DTLA jewelry-district floors: the cafe LOI is not a lease',
 'I like the basis. I do not like "LOI’d" in a capital call. Bring the executed lease or cut the debt assumption. Adaptive reuse without a tenant is a construction loan wearing a fund''s clothes.',
 'dd', 410, 27, 18, now() - interval '20 hours'),
((select id from communities where slug='wheels'), 'Marcus Hale', 'mhale', 'fourth',
 'Rally Book One is not a garage flex',
 'Exhibition fees covered 60% of storage and insurance last year. The upside is the book; the floor is the tour calendar. If you need liquidity in 18 months, this is the wrong penthouse.',
 'deal', 156, 14, 9, now() - interval '2 days'),
((select id from communities where slug='apartments'), 'Priya Shah', 'priyas', 'penthouse',
 'Poll: would you rather recap kitchens or buy a fifth unit nearby?',
 'Same neighborhood, same manager. I am on kitchens. Concentration is a feature when you already know the block.',
 'poll', 98, 11, 17, now() - interval '8 hours'),
((select id from communities where slug='the-pit'), 'Elena Voss', 'elenav', 'fourth',
 'Income bands are not a caste system',
 'They are a risk stack. Ground can still own Street-to-Suite and Solar. Penthouse is illiquid metal and dirt. If that bothers you, the product is working.',
 'thread', 733, 64, 51, now() - interval '11 hours'),
((select id from communities where slug='franchises'), 'Diego Ortega', 'diegoo', 'second',
 'Same-store at the three units, trailing twelve',
 '+1.8%, +0.4%, −0.9%. The weak one is the freeway off-ramp with a new regional chicken next door. Still covers rent. Do not average them into a hero number.',
 'dd', 204, 6, 12, now() - interval '16 hours'),
((select id from communities where slug='predictions'), 'Amina Ruiz', 'aminar', 'fourth',
 'Fed cut market is a rate bet pretending to be a housing bet',
 'If you are using it to hedge the fourplex, you are one correlation away from looking clever. I am in at 57 because the meeting calendar is crowded, not because Inglewood cares.',
 'market', 167, 22, 15, now() - interval '7 hours'),
((select id from communities where slug='the-pit'), 'Jonah Park', 'jpark', 'ground',
 'New here. Put $200 in Street-to-Suite and $50 on occupancy YES.',
 'If the floor is a social network that owns things, this is the smallest adult way in. Tell me if I am being a tourist.',
 'thread', 612, 18, 36, now() - interval '1 hour'),
((select id from communities where slug='due-diligence'), 'Theo Brandt', 'tbrandt', 'second',
 'Crenshaw Solar interconnection log, week 12',
 '19 of 40 PTOs. Two roofs failed inspection (not structure — panel spacing). Still think 80% this year is a coin flip, which is why the market is 44.',
 'dd', 143, 4, 8, now() - interval '12 hours');

insert into comments (post_id, author_name, author_handle, body, upvotes, created_at) values
((select id from posts where title like 'The floor is not a brokerage%'), 'Marcus Hale', 'mhale', 'Correct. The Pit is a room with a door to the asset. If you want a feed that pays you to post, you are in the wrong house.', 88, now() - interval '2 hours'),
((select id from posts where title like 'The floor is not a brokerage%'), 'Jonah Park', 'jpark', 'Understood. I will keep the tourist money in Commons until I have walked a building.', 41, now() - interval '90 minutes'),
((select id from posts where title like 'Inglewood Fourplex — unit mix%'), 'Nia Okonkwo', 'niao', 'The cousin lease is the whole underwrite. March rollover is when this becomes a real 7.', 120, now() - interval '8 hours'),
((select id from posts where title like 'Inglewood Fourplex — unit mix%'), 'Diego Ortega', 'diegoo', 'Walked it in May. Hallway lights are on a timer that does not work. That is a $400 problem pretending to be a vibe.', 64, now() - interval '7 hours'),
((select id from posts where title like 'Income bands are not a caste%'), 'Priya Shah', 'priyas', 'We tried flattening it in the pilot. People with $25 checks wanted into the Prevost. That is how you get angry capital.', 201, now() - interval '10 hours'),
((select id from posts where title like 'New here. Put $200%'), 'Elena Voss', 'elenav', 'Not a tourist. That is exactly the on-ramp. Come to the fourplex walk on Saturday if you can get to Market Street.', 155, now() - interval '40 minutes'),
((select id from posts where title like 'Street-to-Suite just distributed%'), 'Amina Ruiz', 'aminar', 'Credit-union energy is the brand. Please never let this fund chase a 20.', 70, now() - interval '3 hours'),
((select id from posts where title like 'Why I am 61¢ YES%'), 'Theo Brandt', 'tbrandt', 'Sized like a comment is the right size. I am 39¢ NO because insurance is the silent capex.', 33, now() - interval '1 hour');

insert into distributions (vault_id, label, amount_cents, occurred_on) values
((select id from vaults where slug='street-to-suite'), 'Q2 member distribution', 2240000, '2026-07-15'),
((select id from vaults where slug='street-to-suite'), 'Q1 member distribution', 1980000, '2026-04-12'),
((select id from vaults where slug='crenshaw-solar-co'), 'Summer kWh credit', 640000, '2026-08-01'),
((select id from vaults where slug='west-coast-tour-fleet'), 'June lease pass-through', 1860000, '2026-07-02'),
((select id from vaults where slug='golden-arches-socal'), 'Q2 ground rent', 4120000, '2026-07-20'),
((select id from vaults where slug='inglewood-fourplex'), 'May–June NOI', 980000, '2026-07-05');
