/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBazaarRouteImport } from './routes/_app/bazaar'
import { Route as AppMembershipRouteImport } from './routes/_app/membership'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppCommonsIndexRouteImport } from './routes/_app/commons/index'
import { Route as AppCommonsSlugRouteImport } from './routes/_app/commons/$slug'
import { Route as AppFloorsIndexRouteImport } from './routes/_app/floors/index'
import { Route as AppFloorsSlugRouteImport } from './routes/_app/floors/$slug'
import { Route as AppLegalIndexRouteImport } from './routes/_app/legal/index'
import { Route as AppLegalDeleteRouteImport } from './routes/_app/legal/delete'
import { Route as AppLegalPrivacyRouteImport } from './routes/_app/legal/privacy'
import { Route as AppLegalSupportRouteImport } from './routes/_app/legal/support'
import { Route as AppLegalTermsRouteImport } from './routes/_app/legal/terms'
import { Route as AppMarketsIndexRouteImport } from './routes/_app/markets/index'
import { Route as AppMarketsSlugRouteImport } from './routes/_app/markets/$slug'
import { Route as AppPostIdRouteImport } from './routes/_app/post/$id'
import { Route as AppUHandleRouteImport } from './routes/_app/u/$handle'
import { Route as AppVaultsIndexRouteImport } from './routes/_app/vaults/index'
import { Route as AppVaultsSlugRouteImport } from './routes/_app/vaults/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBazaarRoute = AppBazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => AppRoute,
} as any)
const AppMembershipRoute = AppMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppCommonsIndexRoute = AppCommonsIndexRouteImport.update({
  id: '/commons/',
  path: '/commons/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommonsSlugRoute = AppCommonsSlugRouteImport.update({
  id: '/commons/$slug',
  path: '/commons/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorsIndexRoute = AppFloorsIndexRouteImport.update({
  id: '/floors/',
  path: '/floors/',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorsSlugRoute = AppFloorsSlugRouteImport.update({
  id: '/floors/$slug',
  path: '/floors/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalIndexRoute = AppLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalDeleteRoute = AppLegalDeleteRouteImport.update({
  id: '/legal/delete',
  path: '/legal/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalPrivacyRoute = AppLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalSupportRoute = AppLegalSupportRouteImport.update({
  id: '/legal/support',
  path: '/legal/support',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalTermsRoute = AppLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsIndexRoute = AppMarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsSlugRoute = AppMarketsSlugRouteImport.update({
  id: '/markets/$slug',
  path: '/markets/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsSlugRoute = AppVaultsSlugRouteImport.update({
  id: '/vaults/$slug',
  path: '/vaults/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bazaar': typeof AppBazaarRoute
  '/membership': typeof AppMembershipRoute
  '/portfolio': typeof AppPortfolioRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/commons/$slug': typeof AppCommonsSlugRoute
  '/floors/$slug': typeof AppFloorsSlugRoute
  '/legal/delete': typeof AppLegalDeleteRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/support': typeof AppLegalSupportRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/markets/$slug': typeof AppMarketsSlugRoute
  '/post/$id': typeof AppPostIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/vaults/$slug': typeof AppVaultsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/commons/': typeof AppCommonsIndexRoute
  '/floors/': typeof AppFloorsIndexRoute
  '/legal/': typeof AppLegalIndexRoute
  '/markets/': typeof AppMarketsIndexRoute
  '/vaults/': typeof AppVaultsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bazaar': typeof AppBazaarRoute
  '/membership': typeof AppMembershipRoute
  '/portfolio': typeof AppPortfolioRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/commons/$slug': typeof AppCommonsSlugRoute
  '/floors/$slug': typeof AppFloorsSlugRoute
  '/legal/delete': typeof AppLegalDeleteRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/support': typeof AppLegalSupportRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/markets/$slug': typeof AppMarketsSlugRoute
  '/post/$id': typeof AppPostIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/vaults/$slug': typeof AppVaultsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/commons': typeof AppCommonsIndexRoute
  '/floors': typeof AppFloorsIndexRoute
  '/legal': typeof AppLegalIndexRoute
  '/markets': typeof AppMarketsIndexRoute
  '/vaults': typeof AppVaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bazaar': typeof AppBazaarRoute
  '/_app/membership': typeof AppMembershipRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/commons/$slug': typeof AppCommonsSlugRoute
  '/_app/floors/$slug': typeof AppFloorsSlugRoute
  '/_app/legal/delete': typeof AppLegalDeleteRoute
  '/_app/legal/privacy': typeof AppLegalPrivacyRoute
  '/_app/legal/support': typeof AppLegalSupportRoute
  '/_app/legal/terms': typeof AppLegalTermsRoute
  '/_app/markets/$slug': typeof AppMarketsSlugRoute
  '/_app/post/$id': typeof AppPostIdRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/_app/vaults/$slug': typeof AppVaultsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/commons/': typeof AppCommonsIndexRoute
  '/_app/floors/': typeof AppFloorsIndexRoute
  '/_app/legal/': typeof AppLegalIndexRoute
  '/_app/markets/': typeof AppMarketsIndexRoute
  '/_app/vaults/': typeof AppVaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bazaar'
    | '/membership'
    | '/portfolio'
    | '/saved'
    | '/search'
    | '/commons/$slug'
    | '/floors/$slug'
    | '/legal/delete'
    | '/legal/privacy'
    | '/legal/support'
    | '/legal/terms'
    | '/markets/$slug'
    | '/post/$id'
    | '/u/$handle'
    | '/vaults/$slug'
    | '/api/auth/$'
    | '/commons/'
    | '/floors/'
    | '/legal/'
    | '/markets/'
    | '/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bazaar'
    | '/membership'
    | '/portfolio'
    | '/saved'
    | '/search'
    | '/'
    | '/commons/$slug'
    | '/floors/$slug'
    | '/legal/delete'
    | '/legal/privacy'
    | '/legal/support'
    | '/legal/terms'
    | '/markets/$slug'
    | '/post/$id'
    | '/u/$handle'
    | '/vaults/$slug'
    | '/api/auth/$'
    | '/commons'
    | '/floors'
    | '/legal'
    | '/markets'
    | '/vaults'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bazaar'
    | '/_app/membership'
    | '/_app/portfolio'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/'
    | '/_app/commons/$slug'
    | '/_app/floors/$slug'
    | '/_app/legal/delete'
    | '/_app/legal/privacy'
    | '/_app/legal/support'
    | '/_app/legal/terms'
    | '/_app/markets/$slug'
    | '/_app/post/$id'
    | '/_app/u/$handle'
    | '/_app/vaults/$slug'
    | '/api/auth/$'
    | '/_app/commons/'
    | '/_app/floors/'
    | '/_app/legal/'
    | '/_app/markets/'
    | '/_app/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bazaar': {
      id: '/_app/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof AppBazaarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membership': {
      id: '/_app/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AppMembershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commons/': {
      id: '/_app/commons/'
      path: '/commons'
      fullPath: '/commons/'
      preLoaderRoute: typeof AppCommonsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commons/$slug': {
      id: '/_app/commons/$slug'
      path: '/commons/$slug'
      fullPath: '/commons/$slug'
      preLoaderRoute: typeof AppCommonsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/floors/': {
      id: '/_app/floors/'
      path: '/floors'
      fullPath: '/floors/'
      preLoaderRoute: typeof AppFloorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/floors/$slug': {
      id: '/_app/floors/$slug'
      path: '/floors/$slug'
      fullPath: '/floors/$slug'
      preLoaderRoute: typeof AppFloorsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/': {
      id: '/_app/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof AppLegalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/delete': {
      id: '/_app/legal/delete'
      path: '/legal/delete'
      fullPath: '/legal/delete'
      preLoaderRoute: typeof AppLegalDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/privacy': {
      id: '/_app/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof AppLegalPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/support': {
      id: '/_app/legal/support'
      path: '/legal/support'
      fullPath: '/legal/support'
      preLoaderRoute: typeof AppLegalSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal/terms': {
      id: '/_app/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof AppLegalTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets/': {
      id: '/_app/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof AppMarketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets/$slug': {
      id: '/_app/markets/$slug'
      path: '/markets/$slug'
      fullPath: '/markets/$slug'
      preLoaderRoute: typeof AppMarketsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post/$id': {
      id: '/_app/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults/': {
      id: '/_app/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults/$slug': {
      id: '/_app/vaults/$slug'
      path: '/vaults/$slug'
      fullPath: '/vaults/$slug'
      preLoaderRoute: typeof AppVaultsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBazaarRoute: typeof AppBazaarRoute
  AppMembershipRoute: typeof AppMembershipRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommonsSlugRoute: typeof AppCommonsSlugRoute
  AppFloorsSlugRoute: typeof AppFloorsSlugRoute
  AppLegalDeleteRoute: typeof AppLegalDeleteRoute
  AppLegalPrivacyRoute: typeof AppLegalPrivacyRoute
  AppLegalSupportRoute: typeof AppLegalSupportRoute
  AppLegalTermsRoute: typeof AppLegalTermsRoute
  AppMarketsSlugRoute: typeof AppMarketsSlugRoute
  AppPostIdRoute: typeof AppPostIdRoute
  AppUHandleRoute: typeof AppUHandleRoute
  AppVaultsSlugRoute: typeof AppVaultsSlugRoute
  AppCommonsIndexRoute: typeof AppCommonsIndexRoute
  AppFloorsIndexRoute: typeof AppFloorsIndexRoute
  AppLegalIndexRoute: typeof AppLegalIndexRoute
  AppMarketsIndexRoute: typeof AppMarketsIndexRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBazaarRoute: AppBazaarRoute,
  AppMembershipRoute: AppMembershipRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommonsSlugRoute: AppCommonsSlugRoute,
  AppFloorsSlugRoute: AppFloorsSlugRoute,
  AppLegalDeleteRoute: AppLegalDeleteRoute,
  AppLegalPrivacyRoute: AppLegalPrivacyRoute,
  AppLegalSupportRoute: AppLegalSupportRoute,
  AppLegalTermsRoute: AppLegalTermsRoute,
  AppMarketsSlugRoute: AppMarketsSlugRoute,
  AppPostIdRoute: AppPostIdRoute,
  AppUHandleRoute: AppUHandleRoute,
  AppVaultsSlugRoute: AppVaultsSlugRoute,
  AppCommonsIndexRoute: AppCommonsIndexRoute,
  AppFloorsIndexRoute: AppFloorsIndexRoute,
  AppLegalIndexRoute: AppLegalIndexRoute,
  AppMarketsIndexRoute: AppMarketsIndexRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
